---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatservdeployment
  namespace: acaserver
  labels:
    app: chatservdeployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chatservdeployment
  template:
    metadata:
      labels:
        app: chatservdeployment
    spec:
      containers:
      - name: chatservcontainer
        image: localhost:32000/chatservservice:registry
        imagePullPolicy: Always
        ports:
        - containerPort: 8888
---
apiVersion: v1
kind: Service
metadata:
  name: chatservservice
  namespace: acaserver
spec:
  type: NodePort
  selector:
    app: chatservdeployment
  ports:
  - port: 8888
    targetPort: 8888
    nodePort: 30001