---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: restservdeployment
  namespace: acaserver
  labels:
    app: restservdeployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: restservdeployment
  template:
    metadata:
      labels:
        app: restservdeployment
    spec:
      containers:
      - name: restservcontainer
        image: localhost:32000/restservservice:registry
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: restservservice
  namespace: acaserver
spec:
  type: NodePort
  selector:
    app: restservdeployment
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30002